import { GAME_VERSION, SAVE_KEY, REGIONS, CHARACTERS, ITEMS, SKILLS, ENEMIES, ENCOUNTERS, QUESTS, SCENES, CHAPTERS } from './story.js';
const copy = value => JSON.parse(JSON.stringify(value));
const clamp = (n,min,max) => Math.max(min,Math.min(max,n));
const MODES = ['title','explore','dialogue','combat','victory','defeat','ending'];
const SCENE_COMPLETIONS = {
 intro:{flag:'intro',chapter:1},mentor:{flag:'assigned'},notice:{flag:'noticeRead',items:{tea:2,battery:1}},
 postcard:{flag:'postcardRead'},suTalk:{flag:'suTalkRead'},beforeLoop:{battle:'loop'},afterLoop:{chapter:2},
 meetShen:{flag:'metShen'},book:{flag:'bookRead',items:{revive:1}},beforeIndex:{battle:'index'},afterIndex:{chapter:3,join:'shen'},
 beforeRace:{battle:'race'},memory:{flag:'memoryRead',items:{battery:2}},shenTalk:{flag:'shenTalkRead'},
 beforeBeast:{battle:'beast'},beforeCompiler:{battle:'compiler'},finalChoice:{flag:'finished',chapter:4,ending:true}
};
const REQUIREMENTS = {console:'assigned',librarian:'loopCleared',archive:'metShen',sentinel:'checksumSolved',race:'indexCleared',beast:'raceCleared',core:'beastCleared'};
const DONE_FLAGS = {mentor:'assigned',notice:'noticeRead',console:'loopCleared',campusEcho:'postcardRead',suTalk:'suTalkRead',librarian:'metShen',archive:'checksumSolved',sentinel:'indexCleared',book:'bookRead',race:'raceCleared',beast:'beastCleared',core:'compilerCleared',memory:'memoryRead',shenTalk:'shenTalkRead'};
const numeric=(n,min,max)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;

export class Engine {
 constructor(options={}) {
  this.listeners=new Set(); this.options=options; this.lastSaveResult=null; this.state=this._initial(); this._refreshQuests();
 }
 _character(id,level=1){const base=CHARACTERS[id];const growth=level-1;return {...copy(base),level,maxHp:base.maxHp+growth*20,maxMp:base.maxMp+growth*6,atk:base.atk+growth*4,def:base.def+growth*2,hp:base.maxHp+growth*20,mp:base.maxMp+growth*6,shield:0,guarding:false,buff:0};}
 _initial(){return {version:GAME_VERSION,mode:'title',chapter:0,regionId:'campus',player:{...REGIONS.campus.spawn,facing:'down'},party:[this._character('jiang'),this._character('su')],inventory:{tea:4,battery:3,revive:2,rice:1},gold:70,level:1,xp:0,xpNext:45,relationships:{su:0,shen:0},flags:{},quests:[],dialogue:null,battle:null,ending:null,steps:0,battlesWon:0,revision:0};}
 subscribe(listener){this.listeners.add(listener);return ()=>this.listeners.delete(listener);}
 _emit(){this._refreshQuests();this.state.revision++;for(const listener of this.listeners)listener(this.state);if(this.options.autoSave!==false&&this.state.mode!=='title'){this.lastSaveResult=this.save();}}
 _ok(message,extra={}){return {ok:true,message,...extra};}
 _no(message){return {ok:false,message};}
 _refreshQuests(){this.state.quests=QUESTS.map(q=>({...q,status:this.state.flags[q.flag]?'done':(!q.requires||this.state.flags[q.requires])?'active':'locked'}));}
 newGame(){this.state=this._initial();this._openScene('intro');this._emit();return this._ok('旅程開始。');}
 reset(storage){try{(storage??globalThis.localStorage)?.removeItem(SAVE_KEY);}catch{}this.state=this._initial();this._emit();return this._ok('已回到標題畫面。');}
 getRegion(){return REGIONS[this.state.regionId];}
 getObjective(){return this.state.quests.find(q=>q.status==='active')??{title:'一起走向明天',description:'故事已完成。謝謝你與他們同行。',status:'done'};}
 getActiveActor(){if(this.state.mode!=='combat'||!this.state.battle)return null;return this.state.party.find(p=>p.id===this.state.battle.currentActorId)??null;}
 getAvailableRegions(){return Object.values(REGIONS).map(r=>({...r,unlocked:!r.unlockFlag||!!this.state.flags[r.unlockFlag]}));}
 getAvailableInteractions(){return this.getRegion().targets.map(t=>{const required=t.kind==='travel'?REGIONS[t.destination].unlockFlag:REQUIREMENTS[t.id];const locked=!!required&&!this.state.flags[required];return {...t,locked,available:!locked,done:!!this.state.flags[DONE_FLAGS[t.id]],reason:locked?'請先完成目前的主線任務。':'',nearby:Math.abs(t.x-this.state.player.x)+Math.abs(t.y-this.state.player.y)<=1};});}
 getNearbyTargets(){return this.getAvailableInteractions().filter(t=>t.nearby);}
 isWalkable(x,y){const r=this.getRegion();return Number.isInteger(x)&&Number.isInteger(y)&&y>=0&&y<r.map.length&&x>=0&&x<r.map[y].length&&!['#','T','~'].includes(r.map[y][x])&&!r.targets.some(t=>t.x===x&&t.y===y);}
 move(dx,dy){if(this.state.mode!=='explore')return this._no('請先完成目前的對話或戰鬥。');if(![[0,1],[0,-1],[1,0],[-1,0]].some(v=>v[0]===dx&&v[1]===dy))return this._no('一次移動一格。');this.state.player.facing=dx<0?'left':dx>0?'right':dy<0?'up':'down';const {x,y}=this.state.player;if(!this.isWalkable(x+dx,y+dy)){this._emit();return this._no('前方無法通行。');}this.state.player.x+=dx;this.state.player.y+=dy;this.state.steps++;this._emit();return this._ok();}
 _pathTo(x,y,adjacent=false){const start=this.state.player;const queue=[{x:start.x,y:start.y,path:[]}];const seen=new Set([`${start.x},${start.y}`]);for(let i=0;i<queue.length;i++){const p=queue[i];if(adjacent?Math.abs(p.x-x)+Math.abs(p.y-y)<=1:p.x===x&&p.y===y)return p.path;for(const [dx,dy] of [[0,1],[1,0],[0,-1],[-1,0]]){const nx=p.x+dx,ny=p.y+dy,k=`${nx},${ny}`;if(!seen.has(k)&&this.isWalkable(nx,ny)){seen.add(k);queue.push({x:nx,y:ny,path:[...p.path,{x:nx,y:ny}]});}}}return null;}
 _followPath(path){if(path.length){const last=path[path.length-1],previous=path.length>1?path[path.length-2]:this.state.player;this.state.player.facing=last.x<previous.x?'left':last.x>previous.x?'right':last.y<previous.y?'up':'down';this.state.player.x=last.x;this.state.player.y=last.y;this.state.steps+=path.length;}}
 moveTo(x,y){if(this.state.mode!=='explore')return this._no('目前無法移動。');const target=this.getRegion().targets.find(t=>t.x===x&&t.y===y);if(target)return this.interact(target.id);if(!this.isWalkable(x,y))return this._no('這個位置無法通行。');const path=this._pathTo(x,y);if(!path)return this._no('找不到通往這裡的路。');this._followPath(path);this._emit();return this._ok('已前往指定位置。',{path});}
 navigate(targetId){if(this.state.mode!=='explore')return this._no('目前無法移動。');const target=this.getRegion().targets.find(t=>t.id===targetId);if(!target)return this._no('這個地點不在目前區域。');const path=this._pathTo(target.x,target.y,true);if(!path)return this._no('找不到通往這裡的路。');this._followPath(path);this._emit();return this._ok('已抵達。',{path});}
 travel(regionId){if(this.state.mode!=='explore')return this._no('請先結束目前的事件。');const region=REGIONS[regionId];if(!region)return this._no('未知的區域。');if(region.unlockFlag&&!this.state.flags[region.unlockFlag])return this._no('這個區域尚未開啟，請先完成目前的主線任務。');this.state.regionId=regionId;this.state.player={...region.spawn,facing:'up'};this._emit();return this._ok(`已抵達${region.name}。`);}
 interact(targetId){if(this.state.mode!=='explore')return this._no('請先結束目前的事件。');let target=targetId?this.getAvailableInteractions().find(t=>t.id===targetId):this.getNearbyTargets()[0];if(!target)return this._no('附近沒有可互動的對象。');if(target.locked)return this._no(target.reason);if(!target.nearby){const path=this._pathTo(target.x,target.y,true);if(!path)return this._no('無法抵達這個地點。');this._followPath(path);}if(target.kind==='travel')return this.travel(target.destination);if(target.kind==='rest')return this.rest();const f=this.state.flags;let scene;
  switch(target.id){
   case 'mentor':scene=f.assigned?'mentorAgain':'mentor';break;
   case 'notice':scene=f.noticeRead?'noticeAgain':'notice';break;
   case 'console':scene=f.loopCleared?'cleared':'beforeLoop';break;
   case 'campusEcho':scene=f.postcardRead?'noticeAgain':'postcard';break;
   case 'suTalk':scene=f.suTalkRead?'noticeAgain':'suTalk';break;
   case 'librarian':scene=f.metShen?'mentorAgain':'meetShen';break;
   case 'archive':scene=f.checksumSolved?'checksumDone':'checksum';break;
   case 'sentinel':scene=f.indexCleared?'cleared':'beforeIndex';break;
   case 'book':scene=f.bookRead?'noticeAgain':'book';break;
   case 'race':scene=f.raceCleared?'cleared':'beforeRace';break;
   case 'beast':scene=f.beastCleared?'cleared':'beforeBeast';break;
   case 'core':scene=f.compilerCleared?(f.finished?'cleared':'finalChoice'):'beforeCompiler';break;
   case 'memory':scene=f.memoryRead?'noticeAgain':'memory';break;
   case 'shenTalk':scene=f.shenTalkRead?'mentorAgain':'shenTalk';break;
   default:return this._no('這裡暫時很安靜。');
  }this._openScene(scene);this._emit();return this._ok();
 }
 _openScene(sceneId){if(!SCENES[sceneId])throw new Error(`Unknown scene ${sceneId}`);this.state.mode='dialogue';this.state.dialogue={sceneId,index:0,nodes:copy(SCENES[sceneId]),onComplete:copy(SCENE_COMPLETIONS[sceneId]??{})};this._setDialogueNode();}
 _setDialogueNode(){const d=this.state.dialogue,n=d.nodes[d.index];d.speaker=n.speaker;d.text=n.text;d.choices=n.choices??[];d.portrait=Object.values(CHARACTERS).find(p=>p.name===n.speaker)?.portrait??null;d.progress=`${d.index+1} / ${d.nodes.length}`;}
 advanceDialogue(){if(this.state.mode!=='dialogue'||!this.state.dialogue)return this._no('目前沒有對話。');const d=this.state.dialogue;if(d.choices.length)return this._no('請先選擇你的回答。');d.index++;if(d.index<d.nodes.length)this._setDialogueNode();else{const effect=d.onComplete;this.state.dialogue=null;this.state.mode='explore';this._applyEffects(effect);}this._emit();return this._ok();}
 choose(index){if(this.state.mode!=='dialogue'||!this.state.dialogue)return this._no('目前沒有選項。');const d=this.state.dialogue;const c=d.choices[index];if(!Number.isInteger(index)||!c)return this._no('請選擇有效的回答。');this._applyEffects(c.effects??{});d.nodes[d.index]={speaker:'旁白',text:c.response};this._setDialogueNode();this._emit();return this._ok();}
 _applyEffects(effect){if(effect.flag)this.state.flags[effect.flag]=true;if(effect.chapter!==undefined)this.state.chapter=effect.chapter;if(effect.relationship)for(const [id,n] of Object.entries(effect.relationship))this.state.relationships[id]=clamp((this.state.relationships[id]??0)+n,0,10);if(effect.items)for(const[id,n]of Object.entries(effect.items))this.state.inventory[id]=(this.state.inventory[id]??0)+n;if(effect.join&&!this.state.party.some(p=>p.id===effect.join))this.state.party.push(this._character(effect.join,this.state.level));if(typeof effect.ending==='string')this.state.ending=effect.ending;if(effect.battle)this._startBattle(effect.battle);if(effect.ending===true){this.state.mode='ending';this.state.battle=null;this._restore();}}
 continue(){if(this.state.mode==='dialogue')return this.advanceDialogue();if(this.state.mode==='victory')return this.dismissVictory();if(this.state.mode==='defeat')return this.retryBattle();return this._no('目前沒有待繼續的事件。');}
 dismissVictory(){if(this.state.mode!=='victory'||!this.state.battle)return this._no('目前沒有戰鬥結算。');const encounter=ENCOUNTERS[this.state.battle.id];this.state.battle=null;this._openScene(encounter.afterScene);this._emit();return this._ok();}
 _restore(){for(const p of this.state.party){p.hp=p.maxHp;p.mp=p.maxMp;p.shield=0;p.guarding=false;p.buff=0;}}
 rest(){if(this.state.mode!=='explore')return this._no('目前不能休息。');const nearby=this.getNearbyTargets().some(t=>t.kind==='rest');if(!nearby)return this._no('請先前往茶攤、休息席或備援修復站。');this._restore();this._openScene('rest');this._emit();return this._ok('全隊已完全恢復。');}
 buyItem(itemId,quantity=1){if(this.state.mode!=='explore')return this._no('請先結束目前的事件。');if(!this.getNearbyTargets().some(t=>t.kind==='rest'))return this._no('請到休息點補充物資。');const item=ITEMS[itemId];if(!item||!Number.isInteger(quantity)||quantity<1||quantity>99)return this._no('無效的購買數量。');const cost=item.price*quantity;if(this.state.gold<cost)return this._no('潮汐幣不足。休息仍然免費。');this.state.gold-=cost;this.state.inventory[itemId]+=quantity;this._emit();return this._ok(`獲得${item.name} ×${quantity}。`);}
 _resolveAlly(targetId,allowDead=false){return targetId?this.state.party.find(p=>p.id===targetId):allowDead?(this.state.party.find(p=>p.hp<=0)??this.state.party.find(p=>p.hp>0)):[...this.state.party].filter(p=>p.hp>0).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];}
 _applyItem(itemId,targetId){const item=ITEMS[itemId];if(!item||!(this.state.inventory[itemId]>0))return this._no('沒有這項道具。');const target=this._resolveAlly(targetId,item.effect==='revive');if(!target)return this._no('請選擇有效的隊友。');if(item.effect==='revive'&&target.hp>0)return this._no('重啟羽籤只適用於倒下的同伴。');if(item.effect!=='revive'&&target.hp<=0)return this._no('這項道具無法救起倒下的同伴。');if(item.effect==='heal'&&target.hp===target.maxHp)return this._no('這名同伴的生命已滿。');if(item.effect==='mp'&&target.mp===target.maxMp)return this._no('這名同伴的專注已滿。');if(item.effect==='allHeal'&&this.state.party.filter(p=>p.hp>0).every(p=>p.hp===p.maxHp))return this._no('全隊的生命已滿。');this.state.inventory[itemId]--;if(item.effect==='heal')target.hp=Math.min(target.maxHp,target.hp+item.amount);if(item.effect==='mp')target.mp=Math.min(target.maxMp,target.mp+item.amount);if(item.effect==='revive')target.hp=Math.ceil(target.maxHp*item.amount);if(item.effect==='allHeal')for(const p of this.state.party)if(p.hp>0)p.hp=Math.min(p.maxHp,p.hp+item.amount);return this._ok(`使用${item.name}${item.target==='allAllies'?'，全隊恢復生命。':`，照顧${target.name}。`}`);}
 useItem(itemId,targetId){if(this.state.mode==='combat')return this.combatAction({kind:'item',itemId,targetId});if(this.state.mode!=='explore')return this._no('目前不能使用道具。');const result=this._applyItem(itemId,targetId);if(result.ok)this._emit();return result;}
 _startBattle(id,retry=null){const enc=ENCOUNTERS[id];const snapshot=retry??{inventory:copy(this.state.inventory),party:copy(this.state.party),gold:this.state.gold};for(const p of this.state.party){p.shield=0;p.guarding=false;p.buff=0;}this.state.mode='combat';this.state.dialogue=null;this.state.battle={id,name:enc.name,enemies:enc.enemyIds.map(e=>({...copy(ENEMIES[e]),hp:ENEMIES[e].maxHp,shield:0,weakened:0,intent:null,intentText:'',overloaded:false})),round:1,turnOrder:this.state.party.filter(p=>p.hp>0).map(p=>p.id),turnIndex:0,currentActorId:null,log:[`${enc.name}。觀察敵人的意圖，再決定出手順序。`],reward:null,retry:snapshot};if(this.state.battle.turnOrder.length===0)this._restore();this._beginRound();}
 _beginRound(){const b=this.state.battle;b.turnOrder=this.state.party.filter(p=>p.hp>0).map(p=>p.id);b.turnIndex=0;b.currentActorId=b.turnOrder[0]??null;for(const p of this.state.party)p.guarding=false;this._updateIntents();}
 _updateIntents(){const b=this.state.battle;const live=this.state.party.filter(p=>p.hp>0);b.enemies.forEach((e,i)=>{if(e.hp<=0){e.intent={kind:'down',label:'已平息',description:'不再行動。',targetIds:[]};e.intentText=e.intent.label;return;}const kind=e.pattern[(b.round-1)%e.pattern.length];const target=live[(b.round-1+i)%Math.max(live.length,1)];const labels={attack:'鎖定攻擊',charge:'正在蓄力',heavy:'猛烈重擊',sweep:'全體衝擊',shield:'重建護盾'};const detail={attack:`即將攻擊${target?.shortName??'隊伍'}。`,charge:'本回合不攻擊；下一回合將釋放強力招式。',heavy:`重擊${target?.shortName??'隊伍'}；建議防禦或削弱。`,sweep:'即將攻擊全隊；建議護盾、治療或防禦。',shield:'本回合不攻擊，獲得 24 點護盾。'};e.intent={kind,label:labels[kind],description:detail[kind],targetIds:kind==='sweep'?live.map(p=>p.id):target?[target.id]:[]};e.intentText=`${labels[kind]} · ${detail[kind]}`;});}
 _log(text){const b=this.state.battle;if(b){b.log.push(text);if(b.log.length>100)b.log=b.log.slice(-100);}}
 _damageEnemy(enemy,amount){let damage=Math.max(1,Math.round(amount));const absorbed=Math.min(enemy.shield,damage);enemy.shield-=absorbed;damage-=absorbed;enemy.hp=Math.max(0,enemy.hp-damage);return {damage,absorbed};}
 _damageAlly(actor,amount){let damage=Math.max(1,Math.round(amount*(actor.guarding?.42:1)));const absorbed=Math.min(actor.shield,damage);actor.shield-=absorbed;damage-=absorbed;actor.hp=Math.max(0,actor.hp-damage);return {damage,absorbed};}
 _attack(actor,enemy,power=1,ignoreDef=false){const bonus=actor.buff>0?1.35:1;actor.buff=0;const hit=this._damageEnemy(enemy,actor.atk*power*bonus-enemy.def*(ignoreDef?.5:1));this._log(`${actor.name} → ${enemy.name}：${hit.damage} 傷害${hit.absorbed?`（護盾吸收 ${hit.absorbed}）`:''}。`);if(enemy.hp<=0)this._log(`${enemy.name}的異常已平息。`);}
 _skill(actor,skillId,targetId){const skill=SKILLS[skillId];if(!skill||!actor.skills.includes(skillId))return this._no('這名同伴不會這項技能。');if(actor.level<(skill.unlockLevel??1))return this._no(`此技能需要等級 ${skill.unlockLevel}。`);if(actor.mp<skill.cost)return this._no('專注不足。普通攻擊回復 3 點，防禦回復 6 點。');let target;if(skill.target==='enemy'){target=targetId?this.state.battle.enemies.find(e=>e.id===targetId&&e.hp>0):this.state.battle.enemies.find(e=>e.hp>0);if(!target)return this._no('請選擇存活的敵人。');}if(skill.target==='ally'){target=this._resolveAlly(targetId,skill.effect==='revive');if(!target||target.hp<=0&&skill.effect!=='revive')return this._no('請選擇存活的隊友；倒下者需要記憶回溯或重啟羽籤。');}actor.mp-=skill.cost;this._log(`${actor.name}施展「${skill.name}」。`);if(skill.target==='enemy'){this._attack(actor,target,skill.power,skillId==='prism');if(skill.effect==='weaken'&&target.hp>0){target.weakened=1;this._log(`${target.name}的下一次攻擊被削弱。`);}}if(skill.target==='allEnemies')for(const enemy of this.state.battle.enemies)if(enemy.hp>0)this._attack(actor,enemy,skill.power);if(skill.effect==='heal')target.hp=Math.min(target.maxHp,target.hp+58+4*(actor.level-1));if(skill.effect==='revive')target.hp=target.hp<=0?Math.ceil(target.maxHp*.45):Math.min(target.maxHp,target.hp+55);if(skill.effect==='inspire')for(const p of this.state.party)if(p.hp>0){p.hp=Math.min(p.maxHp,p.hp+22);p.buff=1;}if(skill.effect==='shield')for(const p of this.state.party)if(p.hp>0)p.shield=Math.min(66,p.shield+22);if(skill.effect==='sync')for(const p of this.state.party)if(p.hp>0){p.hp=Math.min(p.maxHp,p.hp+14);p.mp=Math.min(p.maxMp,p.mp+8);}return this._ok();}
 combatAction({actorId,kind,skillId,itemId,targetId}={}){if(this.state.mode!=='combat')return this._no('目前不在戰鬥中。');const actor=this.getActiveActor();if(!actor||actor.hp<=0)return this._no('目前沒有可行動的角色。');if(actorId&&actorId!==actor.id)return this._no(`目前輪到${actor.name}。`);if(kind==='flee')return this.fleeBattle();if(kind==='attack'){const enemy=targetId?this.state.battle.enemies.find(e=>e.id===targetId&&e.hp>0):this.state.battle.enemies.find(e=>e.hp>0);if(!enemy)return this._no('請選擇存活的敵人。');this._attack(actor,enemy);actor.mp=Math.min(actor.maxMp,actor.mp+3);}else if(kind==='guard'){actor.guarding=true;actor.mp=Math.min(actor.maxMp,actor.mp+6);this._log(`${actor.name}採取防禦，下一輪傷害降低 58%，回復 6 點專注。`);}else if(kind==='skill'){const result=this._skill(actor,skillId,targetId);if(!result.ok)return result;}else if(kind==='item'){const result=this._applyItem(itemId,targetId);if(!result.ok)return result;this._log(`${actor.name}${result.message}`);}else return this._no('未知的戰鬥指令。');if(this._checkVictory()){this._emit();return this._ok('戰鬥勝利。');}this._nextTurn();this._emit();return this._ok();}
 _nextTurn(){const b=this.state.battle;b.turnIndex++;while(b.turnIndex<b.turnOrder.length&&!this.state.party.some(p=>p.id===b.turnOrder[b.turnIndex]&&p.hp>0))b.turnIndex++;if(b.turnIndex<b.turnOrder.length){b.currentActorId=b.turnOrder[b.turnIndex];return;}this._enemyTurn();if(this.state.mode==='combat'){b.round++;this._beginRound();}}
 _enemyTurn(){const b=this.state.battle;for(const [index,enemy]of b.enemies.entries()){if(enemy.hp<=0)continue;let live=this.state.party.filter(p=>p.hp>0);if(!live.length)break;if(enemy.id==='compiler'&&enemy.hp<=enemy.maxHp/2&&!enemy.overloaded){enemy.overloaded=true;this._log('失序編譯者進入過載：攻擊力提高 20%。');}const intent=enemy.intent;const kind=intent.kind;if(kind==='charge'){this._log(`${enemy.name}正在蓄力，下一輪請提高警覺。`);continue;}if(kind==='shield'){enemy.shield=Math.min(48,enemy.shield+24);this._log(`${enemy.name}獲得 24 點護盾。`);continue;}const modifier=(kind==='heavy'?1.85:kind==='sweep'?.82:1)*(enemy.weakened?.6:1)*(enemy.overloaded?1.2:1);let targets=kind==='sweep'?live:[this.state.party.find(p=>p.id===intent.targetIds[0]&&p.hp>0)??live[(b.round-1+index)%live.length]];for(const target of targets){const hit=this._damageAlly(target,enemy.atk*modifier-target.def);this._log(`${enemy.name}的${intent.label} → ${target.name}：${hit.damage} 傷害${hit.absorbed?`（護盾吸收 ${hit.absorbed}）`:''}${target.hp<=0?'，暫時倒下':' ' }。`);}if(enemy.weakened)enemy.weakened=0;}if(!this.state.party.some(p=>p.hp>0)){this.state.mode='defeat';b.currentActorId=null;this._log('隊伍暫時無法繼續。重新挑戰會恢復全隊與戰前物資，不會失去進度。');}}
 _checkVictory(){const b=this.state.battle;if(!b.enemies.every(e=>e.hp<=0))return false;const enc=ENCOUNTERS[b.id];this.state.flags[enc.flag]=true;this.state.battlesWon++;this.state.gold+=enc.gold;this.state.xp+=enc.xp;const oldLevel=this.state.level;while(this.state.level<8&&this.state.xp>=this.state.xpNext){this.state.xp-=this.state.xpNext;this.state.level++;this.state.xpNext=45+35*(this.state.level-1);}if(this.state.level!==oldLevel){for(let i=0;i<this.state.party.length;i++){const p=this.state.party[i];this.state.party[i]=this._character(p.id,this.state.level);}this._log(`全隊提升至等級 ${this.state.level}，生命與專注完全恢復！`);}else for(const p of this.state.party){p.hp=Math.min(p.maxHp,Math.max(p.hp,1)+Math.ceil(p.maxHp*.15));p.mp=Math.min(p.maxMp,p.mp+8);p.shield=0;p.guarding=false;p.buff=0;}this.state.inventory.tea++;b.reward={xp:enc.xp,gold:enc.gold,items:{tea:1},levelUp:this.state.level-oldLevel,level:this.state.level};b.currentActorId=null;this.state.mode='victory';this._log(`獲得 ${enc.xp} 經驗、${enc.gold} 潮汐幣、暖心紅茶 ×1。`);return true;}
 retryBattle(){if(this.state.mode!=='defeat'||!this.state.battle)return this._no('目前沒有失敗的戰鬥。');const b=this.state.battle,snapshot=copy(b.retry);this.state.inventory=copy(snapshot.inventory);this.state.gold=snapshot.gold;this.state.party=copy(snapshot.party);this._restore();this._startBattle(b.id,snapshot);this._emit();return this._ok('全隊與戰前物資已恢復，再試一次。');}
 fleeBattle(){if(!['combat','defeat'].includes(this.state.mode)||!this.state.battle)return this._no('目前無法撤退。');this.state.mode='explore';this.state.battle=null;for(const p of this.state.party){p.hp=Math.max(1,p.hp);p.shield=0;p.guarding=false;p.buff=0;}this._emit();return this._ok('已安全撤退。可前往休息點，準備好再挑戰。');}
 retreat(){const result=this.fleeBattle();if(!result.ok)return result;const rest=this.getRegion().targets.find(t=>t.kind==='rest');if(rest)this.navigate(rest.id);return this._ok('已撤回安全休息點。與休息點互動即可免費恢復全隊。');}
 getEnding(){const high=this.state.relationships.su>=5&&this.state.relationships.shen>=4;return {title:this.state.ending==='open'?'留白的明天':'與你同行',subtitle:high?'真心相繫・海風裡的約定':'潮汐平息・新的起點',text:this.state.ending==='open'?'他們替每一份未完成保留了位置。程式最後的留白，成為大家重新出發的地方。':'從此，每一次重要的改變，都會先等到大家點頭。三個人的故事，在海風裡繼續編寫。',epilogue:high?'映禾把晚餐後的看海行程，設成沒有截止日的約定。以澄第一次關掉備份提醒，笑著說：「明天再做也來得及。」':'映禾把新的介面畫在餐巾紙上，以澄替它取名為「明天」。彥廷合上電腦，決定先把眼前的夜色記住。',relationships:copy(this.state.relationships),battlesWon:this.state.battlesWon,level:this.state.level,steps:this.state.steps};}
 exportSave(){return JSON.stringify({version:GAME_VERSION,savedAt:new Date().toISOString(),state:this.state});}
 _validateSave(payload){
  const record=v=>v&&typeof v==='object'&&!Array.isArray(v);
  const whole=(n,min,max)=>Number.isInteger(n)&&numeric(n,min,max);
  const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
  const fail=message=>{throw new Error(message);};
  if(!record(payload)||payload.version!==GAME_VERSION||!record(payload.state))fail('存檔版本不相容。');
  const s=payload.state;
  if(s.version!==GAME_VERSION||!MODES.includes(s.mode)||s.mode==='title'||!REGIONS[s.regionId]||!whole(s.chapter,0,4))fail('存檔內容不完整。');
  const region=REGIONS[s.regionId];
  if(!record(s.player)||!whole(s.player.x,0,14)||!whole(s.player.y,0,10)||!['up','down','left','right'].includes(s.player.facing)||['#','T','~'].includes(region.map[s.player.y][s.player.x])||region.targets.some(t=>t.x===s.player.x&&t.y===s.player.y))fail('存檔位置無效。');
  if(!whole(s.level,1,8)||!whole(s.gold,0,1000000)||!whole(s.xp,0,100000)||s.xpNext!==45+35*(s.level-1)||!whole(s.steps,0,10000000)||!whole(s.battlesWon,0,100)||!whole(s.revision,0,10000000))fail('存檔成長資料無效。');
  const validateParty=(party,label,level=s.level)=>{
   if(!Array.isArray(party)||party.length<2||party.length>3||party.some(p=>!record(p))||new Set(party.map(p=>p.id)).size!==party.length||!party.some(p=>p.id==='jiang')||!party.some(p=>p.id==='su'))fail(label);
   for(const p of party){const expected=CHARACTERS[p.id]?this._character(p.id,level):null;if(!whole(level,1,8)||!expected||p.level!==level||p.maxHp!==expected.maxHp||p.maxMp!==expected.maxMp||p.atk!==expected.atk||p.def!==expected.def||!whole(p.hp,0,p.maxHp)||!whole(p.mp,0,p.maxMp)||!whole(p.shield,0,66)||!whole(p.buff,0,1)||typeof p.guarding!=='boolean'||!same(p.skills,expected.skills)||typeof p.name!=='string'||typeof p.shortName!=='string')fail(label);}
  };
  const validateInventory=(inventory,label)=>{if(!record(inventory)||Object.keys(inventory).length!==Object.keys(ITEMS).length||Object.keys(ITEMS).some(k=>!whole(inventory[k],0,99999)))fail(label);};
  validateParty(s.party,'存檔角色資料無效。');validateInventory(s.inventory,'存檔物品資料無效。');
  const allowedFlags=new Set(['intro','assigned','noticeRead','postcardRead','suTalkRead','metShen','checksumSolved','bookRead','memoryRead','shenTalkRead','promisedSea','finished',...Object.values(ENCOUNTERS).map(e=>e.flag)]);
  if(!record(s.flags)||Object.entries(s.flags).some(([k,v])=>!allowedFlags.has(k)||typeof v!=='boolean')||!record(s.relationships)||!whole(s.relationships.su,0,10)||!whole(s.relationships.shen,0,10)||![null,'together','open'].includes(s.ending))fail('存檔故事資料無效。');
  if(region.unlockFlag&&!s.flags[region.unlockFlag])fail('存檔區域尚未開啟。');
  if(s.mode==='ending'&&(!s.flags.finished||!s.flags.compilerCleared||s.chapter!==4||!s.ending))fail('存檔結局資料無效。');
  if(s.mode==='dialogue'){
   const d=s.dialogue,source=record(d)?SCENES[d.sceneId]:null;
   if(!source||!Array.isArray(d.nodes)||d.nodes.length!==source.length||!whole(d.index,0,source.length-1)||!same(d.onComplete,SCENE_COMPLETIONS[d.sceneId]??{}))fail('存檔對話資料無效。');
   for(let i=0;i<source.length;i++){const node=d.nodes[i],original=source[i];const valid=same(node,original)||(original.choices??[]).some(c=>same(node,{speaker:'旁白',text:c.response}));if(!valid)fail('存檔對話內容無效。');}
  }else if(s.dialogue!==null)fail('存檔對話狀態不一致。');
  if(['combat','victory','defeat'].includes(s.mode)){
   const b=s.battle,enc=record(b)?ENCOUNTERS[b.id]:null;
   if(!enc||!Array.isArray(b.enemies)||b.enemies.length!==enc.enemyIds.length||!whole(b.round,1,100000)||!Array.isArray(b.log)||b.log.length>100||b.log.some(l=>typeof l!=='string')||!record(b.retry)||!Array.isArray(b.turnOrder)||new Set(b.turnOrder).size!==b.turnOrder.length||b.turnOrder.some(id=>!s.party.some(p=>p.id===id))||!whole(b.turnIndex,0,s.party.length)||typeof b.name!=='string')fail('存檔戰鬥資料無效。');
   validateParty(b.retry.party,'存檔重試隊伍無效。',s.mode==='victory'?s.level-(b.reward?.levelUp??0):s.level);validateInventory(b.retry.inventory,'存檔重試物品無效。');
   if(!whole(b.retry.gold,0,1000000)||!same(b.retry.party.map(p=>p.id),s.party.map(p=>p.id)))fail('存檔重試資料無效。');
   for(let i=0;i<b.enemies.length;i++){
    const e=b.enemies[i],base=ENEMIES[enc.enemyIds[i]];
    if(!record(e)||e.id!==base.id||e.maxHp!==base.maxHp||e.atk!==base.atk||e.def!==base.def||!same(e.pattern,base.pattern)||!whole(e.hp,0,base.maxHp)||!whole(e.shield,0,48)||!whole(e.weakened,0,1)||typeof e.overloaded!=='boolean'||typeof e.name!=='string'||typeof e.intentText!=='string'||!record(e.intent)||!['attack','charge','heavy','sweep','shield','down'].includes(e.intent.kind)||typeof e.intent.label!=='string'||typeof e.intent.description!=='string'||!Array.isArray(e.intent.targetIds)||e.intent.targetIds.some(id=>!s.party.some(p=>p.id===id))||!e.intent.targetIds.length&&['attack','heavy','sweep'].includes(e.intent.kind))fail('存檔敵人資料無效。');
   }
   if(s.mode==='combat'&&(!s.party.some(p=>p.id===b.currentActorId&&p.hp>0)||b.turnOrder[b.turnIndex]!==b.currentActorId||!b.enemies.some(e=>e.hp>0)))fail('存檔回合資料無效。');
   if(s.mode==='defeat'&&(s.party.some(p=>p.hp>0)||b.currentActorId!==null))fail('存檔戰敗資料無效。');
   if(s.mode==='victory'&&(!b.enemies.every(e=>e.hp===0)||!record(b.reward)||b.reward.xp!==enc.xp||b.reward.gold!==enc.gold))fail('存檔勝利資料無效。');
  }else if(s.battle!==null)fail('存檔戰鬥狀態不一致。');
  return s;
 }
 importSave(json){try{if(typeof json!=='string'||json.length>3000000)return this._no('存檔格式無效。');const payload=JSON.parse(json);const next=copy(this._validateSave(payload));this.state=next;if(next.mode==='dialogue')this._setDialogueNode();this._emit();return this._ok('進度已讀取。');}catch(error){return this._no(`無法讀取存檔：${error.message}`);}}
 save(storage){try{const target=storage??globalThis.localStorage;if(!target||typeof target.setItem!=='function')return this._no('這個環境不支援本機儲存。');if(this.state.mode==='title')return this._no('開始旅程後才能存檔。');target.setItem(SAVE_KEY,this.exportSave());return this._ok('進度已儲存在此裝置。');}catch{return this._no('儲存失敗，可能是瀏覽器封鎖儲存或空間不足。');}}
 load(storage){try{const target=storage??globalThis.localStorage;const raw=target?.getItem(SAVE_KEY);if(!raw)return this._no('這個裝置尚無存檔。');return this.importSave(raw);}catch{return this._no('無法存取這個裝置的存檔。');}}
 getSaveSummary(storage){try{const raw=(storage??globalThis.localStorage)?.getItem(SAVE_KEY);if(!raw)return null;const p=JSON.parse(raw);this._validateSave(p);return {savedAt:p.savedAt,chapter:p.state.chapter,chapterTitle:CHAPTERS[p.state.chapter].title,region:REGIONS[p.state.regionId].name,level:p.state.level,mode:p.state.mode};}catch{return null;}}
}
export default Engine;
