import assert from 'node:assert/strict';
import { Sound } from './audio.js';

const results=[];
async function test(name, fn){try{await fn();results.push({name,ok:true});console.log(`PASS ${name}`)}catch(error){results.push({name,ok:false,error:error.message});console.error(`FAIL ${name}: ${error.stack}`)}}
function fakeAudio({resumePending=false,rejectResume=false}={}){
 const originals=Object.fromEntries(['window','document','setInterval','clearInterval'].map(key=>[key,globalThis[key]]));
 const intervals=new Map(), oscillators=[], gains=[], contexts=[], resumes=[];let serial=0;
 const param=()=>({events:[],setValueAtTime(v,t){this.events.push(['set',v,t])},linearRampToValueAtTime(v,t){this.events.push(['linear',v,t])},exponentialRampToValueAtTime(v,t){this.events.push(['exp',v,t])}});
 class Context{constructor(){this.currentTime=12;this.destination={};this.closed=false;contexts.push(this)}resume(){if(rejectResume)return Promise.reject(new Error('blocked'));if(resumePending)return new Promise(resolve=>resumes.push(resolve));return Promise.resolve()}createOscillator(){const o={frequency:param(),connect(x){this.output=x},start(t){this.started=t},stop(t){this.stopped=t}};oscillators.push(o);return o}createGain(){const g={gain:param(),connect(x){this.output=x}};gains.push(g);return g}close(){this.closed=true;return Promise.resolve()}}
 globalThis.window={AudioContext:Context};globalThis.document={hidden:false};globalThis.setInterval=(fn,ms)=>{const id=++serial;intervals.set(id,{fn,ms});return id};globalThis.clearInterval=id=>intervals.delete(id);
 return {intervals,oscillators,gains,contexts,resumes,restore(){for(const [key,value]of Object.entries(originals)){if(value===undefined)delete globalThis[key];else globalThis[key]=value}}};
}
async function audioTest(options,fn){const fake=fakeAudio(options);try{await fn(fake)}finally{fake.restore()}}
await test('音效預設關閉，不會自動建立音訊環境',()=>audioTest({},async f=>{const s=new Sound();s.tick();s.effect('attack');assert.equal(s.on,false);assert.equal(s.events,0);assert.equal(f.contexts.length,0);assert.equal(f.intervals.size,0)}));
await test('開關音效會建立且清除單一排程',()=>audioTest({},async f=>{const s=new Sound();assert.equal(await s.toggle(),true);assert.equal(f.contexts.length,1);assert.equal(f.intervals.size,1);assert(s.events>0);assert.equal(await s.toggle(),false);assert.equal(f.intervals.size,0);const before=s.events;s.tick();s.effect('win');assert.equal(s.events,before);assert.equal(await s.toggle(),true);assert.equal(f.contexts.length,1);assert.equal(f.intervals.size,1);s.destroy()}));
await test('校園、戰鬥與勝利音效均有有效頻率與包絡排程',()=>audioTest({},async f=>{const s=new Sound();await s.toggle();const campus=s.events;s.scene='combat';s.step=0;s.tick();assert(s.events>=campus+3);s.effect('attack');const before=s.events;s.effect('win');assert.equal(s.events,before+4);s.effect('select');assert.equal(s.events,before+6);s.effect('move');assert.equal(s.events,before+6);assert.equal(f.oscillators.length,f.gains.length);for(let i=0;i<f.oscillators.length;i++){const o=f.oscillators[i],g=f.gains[i];assert(Number.isFinite(o.frequency.events[0][1])&&o.frequency.events[0][1]>0);assert(o.stopped>o.started);assert.equal(o.output,g);assert.equal(g.output,f.contexts[0].destination);assert(g.gain.events.every(([,v,t])=>Number.isFinite(v)&&Number.isFinite(t)));assert(g.gain.events.find(e=>e[0]==='exp')[1]>0)}s.destroy()}));
await test('背景分頁停止新音符',()=>audioTest({},async f=>{const s=new Sound();await s.toggle();const before=s.events;document.hidden=true;s.tick();assert.equal(s.events,before);document.hidden=false;s.tick();assert(s.events>before);s.destroy()}));
await test('瀏覽器拒絕音訊恢復時保持靜音且不排程',()=>audioTest({rejectResume:true},async f=>{const s=new Sound();assert.equal(await s.toggle(),false);assert.equal(s.on,false);assert.equal(f.intervals.size,0);assert.equal(f.oscillators.length,0)}));
await test('快速重複開關不會洩漏排程',()=>audioTest({resumePending:true},async f=>{const s=new Sound();const first=s.toggle(),second=s.toggle();f.resumes.splice(0).forEach(resolve=>resolve());await Promise.all([first,second]);assert(f.intervals.size<=1,`同時存在 ${f.intervals.size} 個音效排程`);if(s.on)await s.toggle();assert.equal(f.intervals.size,0);s.destroy()}));
await test('銷毀音效會停止播放並清除狀態',()=>audioTest({},async f=>{const s=new Sound();await s.toggle();s.destroy();assert.equal(f.intervals.size,0);assert.equal(f.contexts[0].closed,true);assert.equal(s.on,false);assert.equal(s.timer,null);const before=s.events;s.tick();assert.equal(s.events,before)}));

// Static story and map integrity checks.
const {REGIONS,CHARACTERS,SKILLS,ITEMS,SCENES,QUESTS,ENCOUNTERS,ENEMIES}=await import('./story.js');
await test('所有登場可操作人物皆已成年',()=>{for(const c of Object.values(CHARACTERS)){assert(c.age>=18);assert(c.maxHp>0);assert(c.maxMp>0);for(const id of c.skills)assert(SKILLS[id],id)}});
await test('所有地圖尺寸固定且任務地點可接近',()=>{for(const r of Object.values(REGIONS)){const h=r.map.length,w=r.map[0].length;assert.equal(h,11);assert.equal(w,15);assert(r.map.every(row=>row.length===w));const walk=(x,y)=>x>=0&&y>=0&&x<w&&y<h&&!['T','#'].includes(r.map[y][x]);assert(walk(r.spawn.x,r.spawn.y));const seen=new Set([`${r.spawn.x},${r.spawn.y}`]),q=[r.spawn];for(let i=0;i<q.length;i++)for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=q[i].x+dx,y=q[i].y+dy,k=`${x},${y}`;if(walk(x,y)&&!seen.has(k)){seen.add(k);q.push({x,y})}}for(const t of r.targets){assert(t.x>=0&&t.y>=0&&t.x<w&&t.y<h);assert([[0,0],[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>seen.has(`${t.x+dx},${t.y+dy}`)),`${r.id}/${t.id} 無法接近`);if(t.destination)assert(REGIONS[t.destination])}}});
await test('任務、戰鬥與劇情參照完整',()=>{const flagSet=new Set(QUESTS.map(q=>q.flag));assert.equal(flagSet.size,QUESTS.length);for(const q of QUESTS){assert(REGIONS[q.regionId].targets.some(t=>t.id===q.targetId),q.id);if(q.requires)assert(flagSet.has(q.requires),q.requires)}for(const e of Object.values(ENCOUNTERS)){assert(SCENES[e.afterScene]);assert(flagSet.has(e.flag));for(const id of e.enemyIds)assert(ENEMIES[id])}for(const [id,nodes]of Object.entries(SCENES)){assert(nodes.length>0,id);for(const n of nodes){assert(n.speaker&&n.text);if(n.choices){assert(n.choices.length>=2);for(const c of n.choices){assert(c.text&&c.response);for(const who of Object.keys(c.effects.relationship??{}))assert(CHARACTERS[who])}}}}});
await test('技能及道具目標與消耗皆有效',()=>{const targets=['enemy','allEnemies','ally','allAllies'];for(const s of Object.values(SKILLS)){assert(targets.includes(s.target));assert(Number.isInteger(s.cost)&&s.cost>0);assert(s.description)}for(const i of Object.values(ITEMS)){assert(targets.includes(i.target));assert(i.price>0);assert(i.amount>0)}});

// Engine, story, persistence, and DOM integration tests are appended below.

console.log(`\n額外 QA：${results.filter(r=>r.ok).length}/${results.length} 通過。`);
if(results.some(r=>!r.ok))process.exitCode=1;
