import assert from 'node:assert/strict';
import { Sound } from './audio.js';

const results=[];
async function test(name, fn){try{await fn();results.push({name,ok:true});console.log(`PASS ${name}`)}catch(error){results.push({name,ok:false,error:error.message});console.error(`FAIL ${name}: ${error.stack}`)}}
function fakeAudio({resumePending=false,rejectResume=false}={}){
 const originals=Object.fromEntries(['window','document','setInterval','clearInterval'].map(key=>[key,globalThis[key]]));
 const intervals=new Map(), oscillators=[], gains=[], contexts=[], resumes=[];let serial=0;
 const param=()=>({events:[],setValueAtTime(v,t){this.events.push(['set',v,t])},linearRampToValueAtTime(v,t){this.events.push(['linear',v,t])},exponentialRampToValueAtTime(v,t){this.events.push(['exp',v,t])}});
 class Context{constructor(){this.currentTime=12;this.destination={};this.closed=false;contexts.push(this)}resume(){if(rejectResume)return Promise.reject(new Error('blocked'));if(resumePending)return new Promise(resolve=>resumes.push(resolve));return Promise.resolve()}createOscillator(){const o={frequency:param(),connect(x){this.output=x},start(t){this.started=t},stop(t){this.stopped=t}};oscillators.push(o);return o}createGain(){const g={gain:param(),connect(x){this.output=x}};gains.push(g);return g}close(){this.closed=true;return Promise.resolve()}}
 globalThis.window={AudioContext:Context};globalThis.document={hidden:false};globalThis.setInterval=(fn,ms)=>{const id=++serial;intervals.set(id,{fn,ms});return id};globalThis.clearInterval=id=>intervals.delete(id);
 return {intervals,oscillators,gains,contexts,resumes,restore(){for(const [key,value]of Object.entries(originals)){if(value===undefined)delete globalThis[key];else globalThis[key]=value}}};
}
async function audioTest(options,fn){const fake=fakeAudio(options);try{await fn(fake)}finally{fake.restore()}}
await test('音效預設關閉，不會自動建立音訊環境',()=>audioTest({},async f=>{const s=new Sound();s.tick();s.effect('attack');assert.equal(s.on,false);assert.equal(s.events,0);assert.equal(f.contexts.length,0);assert.equal(f.intervals.size,0)}));
await test('開關音效會建立且清除單一排程',()=>audioTest({},async f=>{const s=new Sound();assert.equal(await s.toggle(),true);assert.equal(f.contexts.length,1);assert.equal(f.intervals.size,1);assert(s.events>0);assert.equal(await s.toggle(),false);assert.equal(f.intervals.size,0);const before=s.events;s.tick();s.effect('win');assert.equal(s.events,before);assert.equal(await s.toggle(),true);assert.equal(f.contexts.length,1);assert.equal(f.intervals.size,1);s.destroy()}));
await test('校園、戰鬥與勝利音效均有有效頻率與包絡排程',()=>audioTest({},async f=>{const s=new Sound();await s.toggle();const campus=s.events;s.scene='combat';s.step=0;s.tick();assert(s.events>=campus+3);s.effect('attack');const before=s.events;s.effect('win');assert.equal(s.events,before+4);s.effect('select');assert.equal(s.events,before+6);s.effect('move');assert.equal(s.events,before+6);assert.equal(f.oscillators.length,f.gains.length);for(let i=0;i<f.oscillators.length;i++){const o=f.oscillators[i],g=f.gains[i];assert(Number.isFinite(o.frequency.events[0][1])&&o.frequency.events[0][1]>0);assert(o.stopped>o.started);assert.equal(o.output,g);assert.equal(g.output,f.contexts[0].destination);assert(g.gain.events.every(([,v,t])=>Number.isFinite(v)&&Number.isFinite(t)));assert(g.gain.events.find(e=>e[0]==='exp')[1]>0)}s.destroy()}));
await test('背景分頁停止新音符',()=>audioTest({},async f=>{const s=new Sound();await s.toggle();const before=s.events;document.hidden=true;s.tick();assert.equal(s.events,before);document.hidden=false;s.tick();assert(s.events>before);s.destroy()}));
await test('瀏覽器拒絕音訊恢復時保持靜音且不排程',()=>audioTest({rejectResume:true},async f=>{const s=new Sound();assert.equal(await s.toggle(),false);assert.equal(s.on,false);assert.equal(f.intervals.size,0);assert.equal(f.oscillators.length,0)}));
await test('快速重複開關不會洩漏排程',()=>audioTest({resumePending:true},async f=>{const s=new Sound();const first=s.toggle(),second=s.toggle();f.resumes.splice(0).forEach(resolve=>resolve());await Promise.all([first,second]);assert(f.intervals.size<=1,`同時存在 ${f.intervals.size} 個音效排程`);if(s.on)await s.toggle();assert.equal(f.intervals.size,0);s.destroy()}));
await test('銷毀音效會停止播放並清除狀態',()=>audioTest({},async f=>{const s=new Sound();await s.toggle();s.destroy();assert.equal(f.intervals.size,0);assert.equal(f.contexts[0].closed,true);assert.equal(s.on,false);assert.equal(s.timer,null);const before=s.events;s.tick();assert.equal(s.events,before)}));

// Static story and map integrity checks.
const {REGIONS,CHARACTERS,SKILLS,ITEMS,SCENES,QUESTS,ENCOUNTERS,ENEMIES}=await import('./story.js');
await test('所有登場可操作人物皆已成年',()=>{for(const c of Object.values(CHARACTERS)){assert(c.age>=18);assert(c.maxHp>0);assert(c.maxMp>0);for(const id of c.skills)assert(SKILLS[id],id)}});
await test('所有地圖尺寸固定且任務地點可接近',()=>{for(const r of Object.values(REGIONS)){const h=r.map.length,w=r.map[0].length;assert.equal(h,11);assert.equal(w,15);assert(r.map.every(row=>row.length===w));const walk=(x,y)=>x>=0&&y>=0&&x<w&&y<h&&!['T','#'].includes(r.map[y][x]);assert(walk(r.spawn.x,r.spawn.y));const seen=new Set([`${r.spawn.x},${r.spawn.y}`]),q=[r.spawn];for(let i=0;i<q.length;i++)for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=q[i].x+dx,y=q[i].y+dy,k=`${x},${y}`;if(walk(x,y)&&!seen.has(k)){seen.add(k);q.push({x,y})}}for(const t of r.targets){assert(t.x>=0&&t.y>=0&&t.x<w&&t.y<h);assert([[0,0],[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>seen.has(`${t.x+dx},${t.y+dy}`)),`${r.id}/${t.id} 無法接近`);if(t.destination)assert(REGIONS[t.destination])}}});
await test('任務、戰鬥與劇情參照完整',()=>{const flagSet=new Set(QUESTS.map(q=>q.flag));assert.equal(flagSet.size,QUESTS.length);for(const q of QUESTS){assert(REGIONS[q.regionId].targets.some(t=>t.id===q.targetId),q.id);if(q.requires)assert(flagSet.has(q.requires),q.requires)}for(const e of Object.values(ENCOUNTERS)){assert(SCENES[e.afterScene]);assert(flagSet.has(e.flag));for(const id of e.enemyIds)assert(ENEMIES[id])}for(const [id,nodes]of Object.entries(SCENES)){assert(nodes.length>0,id);for(const n of nodes){assert(n.speaker&&n.text);if(n.choices){assert(n.choices.length>=2);for(const c of n.choices){assert(c.text&&c.response);for(const who of Object.keys(c.effects.relationship??{}))assert(CHARACTERS[who])}}}}});
await test('技能及道具目標與消耗皆有效',()=>{const targets=['enemy','allEnemies','ally','allAllies'];for(const s of Object.values(SKILLS)){assert(targets.includes(s.target));assert(Number.isInteger(s.cost)&&s.cost>0);assert(s.description)}for(const i of Object.values(ITEMS)){assert(targets.includes(i.target));assert(i.price>0);assert(i.amount>0)}});

// Public API story routes and isolated boundary-condition combat fixtures.
const {Engine}=await import('./engine.js');
const clone=v=>JSON.parse(JSON.stringify(v));
const normalized=s=>{const x=clone(s);delete x.revision;return x};
const fresh=()=>new Engine({autoSave:false});
const snapshots={};
const expectOk=r=>assert.equal(r?.ok,true,r?.message);
function drain(e,choices={}){let guard=0;while(e.state.mode==='dialogue'){assert(++guard<80,'對話未能結束');const d=e.state.dialogue;expectOk(d.choices.length?e.choose(choices[d.sceneId]??(d.sceneId==='checksum'?1:0)):e.advanceDialogue())}}
function talk(e,id,choices={}){expectOk(e.interact(id));drain(e,choices)}
function healthy(e){for(const p of e.state.party){assert(Number.isFinite(p.hp)&&p.hp>=0&&p.hp<=p.maxHp,p.id+' HP');assert(Number.isFinite(p.mp)&&p.mp>=0&&p.mp<=p.maxMp,p.id+' MP');assert(p.shield>=0)}for(const n of Object.values(e.state.inventory))assert(Number.isInteger(n)&&n>=0)}
function fight(e){let turns=0;while(e.state.mode==='combat'){assert(++turns<250,'戰鬥未能結束');const a=e.getActiveActor();assert(a?.hp>0);const dead=e.state.party.find(p=>p.hp===0),weak=e.state.party.filter(p=>p.hp>0).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0],enemy=e.state.battle.enemies.find(x=>x.hp>0);let action={actorId:a.id,kind:'attack',targetId:enemy.id};if(dead&&e.state.inventory.revive)action={actorId:a.id,kind:'item',itemId:'revive',targetId:dead.id};else if(weak.hp/weak.maxHp<.33&&e.state.inventory.tea)action={actorId:a.id,kind:'item',itemId:'tea',targetId:weak.id};else if(a.id==='su'&&weak.hp/weak.maxHp<.65&&a.mp>=8)action={actorId:a.id,kind:'skill',skillId:'heal',targetId:weak.id};else if(a.id==='jiang'&&e.state.battle.enemies.filter(x=>x.hp>0).length>1&&a.level>=2&&a.mp>=13)action={actorId:a.id,kind:'skill',skillId:'recursion'};else if(a.id==='jiang'&&a.mp>=7)action={actorId:a.id,kind:'skill',skillId:'debug',targetId:enemy.id};else if(a.id==='shen'&&a.mp>=8)action={actorId:a.id,kind:'skill',skillId:'breakpoint',targetId:enemy.id};else if(a.id==='su'&&a.level>=2&&a.mp>=7)action={actorId:a.id,kind:'skill',skillId:'prism',targetId:enemy.id};expectOk(e.combatAction(action));healthy(e)}assert.equal(e.state.mode,'victory');return turns}
function finishBattle(e,id,choices){assert.equal(e.state.battle.id,id);snapshots[id]??=e.exportSave();fight(e);snapshots[id+'Victory']??=e.exportSave();expectOk(e.dismissVictory());drain(e,choices)}
function route(choices={},optional=true,capture=false){const e=fresh();expectOk(e.newGame());if(capture)snapshots.intro=e.exportSave();drain(e,choices);if(optional){talk(e,'notice');talk(e,'campusEcho',choices);talk(e,'suTalk',choices)}talk(e,'mentor');talk(e,'snack');talk(e,'console');finishBattle(e,'loop',choices);expectOk(e.travel('library'));talk(e,'librarian',choices);talk(e,'archive',choices);if(optional)talk(e,'book');talk(e,'libraryRest');talk(e,'sentinel');finishBattle(e,'index',choices);assert(e.state.party.some(p=>p.id==='shen'));expectOk(e.travel('server'));if(optional){talk(e,'memory');talk(e,'shenTalk',choices)}talk(e,'serverRest');talk(e,'race');finishBattle(e,'race',choices);talk(e,'serverRest');talk(e,'beast');finishBattle(e,'beast',choices);talk(e,'serverRest');talk(e,'core');finishBattle(e,'compiler',choices);assert.equal(e.state.mode,'ending');assert.equal(e.state.battlesWon,5);assert(e.state.quests.every(q=>q.status==='done'));assert(e.state.flags.finished);healthy(e);return e}
await test('完整主線兩種協定 × 高低羈絆四種結局皆可達成',()=>{const seen=new Set();for(const optional of [false,true])for(const ending of [0,1]){const e=route({finalChoice:ending},optional,true);seen.add(e.getEnding().title+'|'+e.getEnding().subtitle);snapshots['ending'+optional+ending]=e.exportSave();assert.equal(e.state.ending,ending?'open':'together')}assert.equal(seen.size,4)});
await test('六組對話分支的全部 64 種組合可走完五場主線戰鬥',()=>{const ids=['intro','postcard','suTalk','meetShen','shenTalk','finalChoice'];for(let mask=0;mask<64;mask++){const choices=Object.fromEntries(ids.map((id,i)=>[id,(mask>>i)&1]));const e=route(choices,true);assert.equal(e.state.ending,choices.finalChoice?'open':'together')}});
await test('所有保存模式可讀回，戰鬥與結算讀回後可繼續',()=>{for(const [name,raw]of Object.entries(snapshots)){const e=fresh();assert.equal(e.importSave(raw).ok,true,name+' 存檔讀取失敗');assert.deepEqual(normalized(e.state),normalized(JSON.parse(raw).state),name);if(e.state.mode==='combat'){fight(e);expectOk(e.dismissVictory());drain(e)}else if(e.state.mode==='victory'){expectOk(e.dismissVictory());drain(e)}else if(e.state.mode==='dialogue')drain(e);healthy(e)}});
await test('主線關卡不允許提前進入，錯誤謎題可無損重試',()=>{const e=fresh();e.newGame();drain(e);assert.equal(e.travel('library').ok,false);assert.equal(e.travel('server').ok,false);assert.equal(e.interact('console').ok,false);talk(e,'mentor');talk(e,'console');finishBattle(e,'loop',{});expectOk(e.travel('library'));assert.equal(e.interact('archive').ok,false);assert.equal(e.interact('sentinel').ok,false);talk(e,'librarian');const inv=clone(e.state.inventory),money=e.state.gold;for(const answer of [0,2]){talk(e,'archive',{checksum:answer});assert(!e.state.flags.checksumSolved);assert.equal(e.interact('sentinel').ok,false);assert.deepEqual(e.state.inventory,inv);assert.equal(e.state.gold,money)}talk(e,'archive',{checksum:1});assert(e.state.flags.checksumSolved);talk(e,'sentinel');finishBattle(e,'index',{});expectOk(e.travel('server'));assert.equal(e.interact('beast').ok,false);assert.equal(e.interact('core').ok,false)});
await test('重複互動與過期選項不重複取得物資或羈絆',()=>{const e=fresh();e.newGame();drain(e);talk(e,'notice');const inv=clone(e.state.inventory);for(let i=0;i<5;i++)talk(e,'notice');assert.deepEqual(e.state.inventory,inv);talk(e,'suTalk');const rel=clone(e.state.relationships);for(let i=0;i<5;i++)talk(e,'suTalk');assert.deepEqual(e.state.relationships,rel);talk(e,'campusEcho');const rel2=clone(e.state.relationships);talk(e,'campusEcho');assert.deepEqual(e.state.relationships,rel2);assert.equal(e.choose(0).ok,false);expectOk(e.interact('mentor'));assert.equal(e.move(1,0).ok,false);assert.equal(e.travel('library').ok,false);assert.equal(e.interact('notice').ok,false)});
await test('選項必須作答且每個選項只能套用一次',()=>{const e=fresh();e.newGame();while(!e.state.dialogue.choices.length)expectOk(e.advanceDialogue());const before=clone(e.state);assert.equal(e.advanceDialogue().ok,false);assert.equal(e.choose(-1).ok,false);assert.equal(e.choose(999).ok,false);assert.equal(e.choose(.5).ok,false);assert.deepEqual(e.state,before);expectOk(e.choose(1));const after=clone(e.state);assert.equal(e.choose(1).ok,false);assert.deepEqual(e.state,after);drain(e);assert.equal(e.state.mode,'explore')});
await test('戰鬥無效技能、目標、低專注及過期角色不消耗行動',()=>{const e=fresh();expectOk(e.importSave(snapshots.loop));for(const action of [{kind:'unknown'},{kind:'attack',targetId:'absent'},{kind:'attack',targetId:'su'},{kind:'skill',skillId:'heal'},{kind:'skill',skillId:'recursion'},{kind:'skill',skillId:'debug',targetId:'absent'},{kind:'item',itemId:'absent'},{kind:'item',itemId:'tea',targetId:'absent'},{kind:'item',itemId:'revive',targetId:'jiang'},{actorId:'su',kind:'guard'}]){const before=clone(e.state);assert.equal(e.combatAction(action).ok,false,JSON.stringify(action));assert.deepEqual(e.state,before)}e.getActiveActor().mp=0;const before=clone(e.state);assert.equal(e.combatAction({kind:'skill',skillId:'debug'}).ok,false);assert.deepEqual(e.state,before);expectOk(e.combatAction({actorId:'jiang',kind:'attack'}));const once=clone(e.state);assert.equal(e.combatAction({actorId:'jiang',kind:'attack'}).ok,false);assert.deepEqual(e.state,once)});
await test('五場戰鬥皆可戰敗、存取、重試或撤回，物資可恢復',()=>{for(const id of Object.keys(ENCOUNTERS)){const e=fresh();expectOk(e.importSave(snapshots[id]));const inventory=clone(e.state.battle.retry.inventory);e.getActiveActor().mp=0;expectOk(e.combatAction({kind:'item',itemId:'battery',targetId:e.getActiveActor().id}));for(const p of e.state.party)p.hp=1;let n=0;while(e.state.mode==='combat'){assert(++n<80);expectOk(e.combatAction({kind:'guard'}))}assert.equal(e.state.mode,'defeat',id);const raw=e.exportSave(),retry=fresh();expectOk(retry.importSave(raw));expectOk(retry.retryBattle());assert.deepEqual(retry.state.inventory,inventory);assert(retry.state.party.every(p=>p.hp===p.maxHp&&p.mp===p.maxMp));fight(retry);const retreat=fresh();expectOk(retreat.importSave(raw));expectOk(retreat.fleeBattle());assert.equal(retreat.state.mode,'explore');assert.equal(retreat.state.battle,null);assert(retreat.state.party.every(p=>p.hp>0));talk(retreat,{campus:'snack',library:'libraryRest',server:'serverRest'}[retreat.state.regionId]);assert(retreat.state.party.every(p=>p.hp===p.maxHp&&p.mp===p.maxMp))}});
await test('探索道具、免費休息與補給消耗正確',()=>{const e=fresh();e.newGame();drain(e);assert.equal(e.rest().ok,false);assert.equal(e.buyItem('tea').ok,false);const p=e.state.party[0];let before=e.state.inventory.tea;assert.equal(e.useItem('tea','jiang').ok,false);assert.equal(e.state.inventory.tea,before);p.hp=1;expectOk(e.useItem('tea','jiang'));assert.equal(p.hp,66);assert.equal(e.state.inventory.tea,before-1);p.mp=0;expectOk(e.useItem('battery','jiang'));assert.equal(p.mp,24);p.hp=0;assert.equal(e.useItem('tea','jiang').ok,false);expectOk(e.useItem('revive','jiang'));assert.equal(p.hp,Math.ceil(p.maxHp*.45));for(const x of e.state.party)x.hp=1;expectOk(e.useItem('rice'));assert(e.state.party.every(x=>x.hp===41));talk(e,'snack');assert(e.state.party.every(x=>x.hp===x.maxHp&&x.mp===x.maxMp));const gold=e.state.gold,count=e.state.inventory.tea;expectOk(e.buyItem('tea',2));assert.equal(e.state.gold,gold-50);assert.equal(e.state.inventory.tea,count+2);for(const quantity of [0,-1,1.5,100,NaN])assert.equal(e.buyItem('tea',quantity).ok,false);assert.equal(e.buyItem('revive',99).ok,false);healthy(e)});
await test('存檔空間失敗、缺少存檔、破損字串皆不改變遊戲',()=>{const e=fresh();e.newGame();drain(e);const before=clone(e.state),data=new Map(),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};expectOk(e.save(storage));const f=fresh();expectOk(f.load(storage));assert.deepEqual(normalized(e.state),normalized(f.state));const throwing={getItem(){throw Error('blocked')},setItem(){throw Error('quota')}};assert.equal(e.save(throwing).ok,false);assert.equal(e.load(throwing).ok,false);assert.equal(e.load({getItem:()=>null}).ok,false);for(const raw of ['',null,{},'null','[]','{','{}','x'.repeat(3000001)])assert.equal(e.importSave(raw).ok,false);assert.deepEqual(e.state,before)});

// Corruption corpus: every rejection must be atomic and leave the current game intact.
const mutations=[
 ['對話後續節點缺失','intro',s=>{s.dialogue.nodes[1]=null}],
 ['對話選項非陣列','intro',s=>{s.dialogue.nodes[0].choices={}}],
 ['對話選項格式錯誤','intro',s=>{s.dialogue.nodes[0].choices=[null]}],
 ['對話完成效果缺失','intro',s=>{delete s.dialogue.onComplete}],
 ['對話加入不存在角色','intro',s=>{s.dialogue.onComplete={join:'missing'}}],
 ['對話數值效果非數字','intro',s=>{s.dialogue.nodes[0].choices=[{text:'x',response:'y',effects:{relationship:{su:'x'}}}]}],
 ['戰鬥敵人意圖缺欄位','loop',s=>{s.battle.enemies[0].intent={}}],
 ['戰鬥敵人攻擊力缺失','loop',s=>{delete s.battle.enemies[0].atk}],
 ['戰鬥敵人護盾缺失','loop',s=>{delete s.battle.enemies[0].shield}],
 ['戰鬥敵人循環為空','loop',s=>{s.battle.enemies[0].pattern=[]}],
 ['戰鬥敵人生命上限缺失','loop',s=>{delete s.battle.enemies[0].maxHp}],
 ['戰鬥隊伍順序重複','loop',s=>{s.battle.turnOrder=['jiang','jiang']}],
 ['戰鬥重試隊伍為空','loop',s=>{s.mode='defeat';s.battle.retry.party=[]}],
 ['戰鬥重試物品缺失','loop',s=>{s.battle.retry.inventory={}}],
 ['戰鬥重試金錢負數','loop',s=>{s.battle.retry.gold=-1}],
 ['角色等級缺失','loop',s=>{delete s.party[0].level}],
 ['角色增益非數字','loop',s=>{s.party[0].buff='x'}],
 ['角色防禦非布林','loop',s=>{s.party[0].guarding='yes'}],
 ['角色站在牆壁','intro',s=>{s.player.x=0;s.player.y=0}],
 ['故事旗標為陣列','intro',s=>{s.flags=[]}],
 ['已結束模式但未完成主線','intro',s=>{s.mode='ending';s.ending='open'}],
 ['計數器缺失','loop',s=>{delete s.steps;delete s.battlesWon}],
];
for(const [name,base,mutate]of mutations)await test('拒絕損毀存檔：'+name,()=>{const p=JSON.parse(snapshots[base]);mutate(p.state);const e=fresh();e.newGame();const before=clone(e.state);assert.equal(e.importSave(JSON.stringify(p)).ok,false,name);assert.deepEqual(e.state,before,'讀取失敗必須保留現有進度')});

// Headless DOM event integration. These stubs test handlers and state, not layout.
const {readFile}=await import('node:fs/promises');
const vm=await import('node:vm');
const appSource=(await readFile(new URL('./app.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
function uiHarness(){
 const data=new Map(),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};
 const handlers={},winHandlers={},errors=[];let game;
 const doc={activeElement:null,hidden:false,addEventListener:(k,fn)=>handlers[k]=fn};
 class Node{constructor(tag='DIV'){this.tagName=tag;this.children=[];this.dataset={};this.listeners={};this.disabled=false;this._html='';this.classList={add(){},remove(){}}}set innerHTML(html){this._html=html;this.children=[];this.buttons=[];this.links=[];this.canvas=null;for(const match of html.matchAll(/<(button|a)\b([^>]*)>([\s\S]*?)<\/\1>/g)){const n=new Node(match[1].toUpperCase());n.textContent=match[3].replace(/<[^>]+>/g,'');n.disabled=/\bdisabled\b/.test(match[2]);n.parent=this;for(const attr of match[2].matchAll(/data-([\w-]+)="([^"]*)"/g))n.dataset[attr[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=attr[2];(n.tagName==='BUTTON'?this.buttons:this.links).push(n)}if(html.includes('id="map"')){this.canvas=new Node('CANVAS');this.canvas.parent=this}}get innerHTML(){return this._html}append(n){n.parent=this;this.children.push(n)}remove(){if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this)}focus(){doc.activeElement=this}closest(tag){return this.tagName===tag.toUpperCase()?this:null}addEventListener(k,fn){this.listeners[k]=fn}querySelector(selector){if(selector==='button')return this.buttons?.[0]??null;return null}getBoundingClientRect(){return {left:0,top:0,width:720,height:528}}}
 const app=new Node(),toast=new Node();doc.activeElement=app;doc.createElement=tag=>new Node(tag.toUpperCase());doc.querySelector=selector=>selector==='#app'?app:selector==='#toast'?toast:selector==='#map'?app.canvas:selector==='.modal-backdrop'?app.children.find(c=>c.className==='modal-backdrop')??null:null;doc.querySelectorAll=()=>{const modal=doc.querySelector('.modal-backdrop');return modal?[...modal.buttons.filter(b=>!b.disabled),...modal.links]:[]};
 class CaptureEngine extends Engine{constructor(){super({autoSave:false});game=this}}
 const context={Engine:CaptureEngine,Sound,REGIONS,CHARACTERS,ITEMS,SKILLS,CHAPTERS:(awaitedStory.CHAPTERS),DISCLAIMER:awaitedStory.DISCLAIMER,SAVE_KEY:awaitedStory.SAVE_KEY,drawMap(){},enemySvg(){return '<svg></svg>'},document:doc,localStorage:storage,window:{addEventListener:(k,fn)=>winHandlers[k]=fn},setTimeout(){return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){},console:{...console,error:(...args)=>errors.push(args)}};
 vm.runInNewContext(appSource,context,{filename:'app.js'});
 function buttons(){const modal=doc.querySelector('.modal-backdrop');return modal?modal.buttons:app.buttons}
 function find(dataset){return buttons().find(b=>Object.entries(dataset).every(([k,v])=>b.dataset[k]===String(v)))}
 async function click(dataset){const b=find(dataset);assert(b,`找不到按鈕 ${JSON.stringify(dataset)}`);await app.listeners.click({target:b});return b}
 function key(key,extra={}){const event={key,repeat:false,shiftKey:false,target:doc.activeElement??app,preventDefault(){this.prevented=true},...extra};handlers.keydown(event);return event}
 return {get game(){return game},app,doc,storage,data,toast,errors,click,key,find,winHandlers,render:()=>vm.runInNewContext('render()',context)};
}
const awaitedStory=await import('./story.js');
await test('介面：作品資訊、旅途說明與 Esc 關閉不改變遊戲',async()=>{const u=uiHarness();assert.equal(u.game.state.mode,'title');await u.click({action:'credits'});assert(u.doc.querySelector('.modal-backdrop').innerHTML.includes('成年'));await u.click({action:'close'});assert.equal(u.game.state.mode,'title');await u.click({action:'new'});const before=clone(u.game.state);await u.click({action:'help'});assert(u.doc.querySelector('.modal-backdrop').innerHTML.includes('旅途指南'));u.key('Escape');assert.equal(u.doc.querySelector('.modal-backdrop'),null);assert.deepEqual(u.game.state,before);assert.equal(u.errors.length,0)});
await test('介面：新旅程、選項、防連按、暫停與恢復',async()=>{const u=uiHarness();await u.click({action:'new'});assert.equal(u.game.state.mode,'dialogue');const index=u.game.state.dialogue.index;u.key('Enter',{target:u.app,repeat:true});assert.equal(u.game.state.dialogue.index,index);while(!u.game.state.dialogue.choices.length)await u.click({action:'advance'});const before=u.game.state.dialogue.index;u.key('Enter',{target:u.app});assert.equal(u.game.state.dialogue.index,before);u.key('Escape');assert(u.doc.querySelector('.modal-backdrop'));u.key('ArrowLeft',{target:u.app});assert.equal(u.game.state.dialogue.index,before);u.key('Escape');assert.equal(u.doc.querySelector('.modal-backdrop'),null);await u.click({choice:'1'});assert.equal(u.game.state.relationships.su,1);while(u.game.state.mode==='dialogue')await u.click({action:'advance'});assert.equal(u.game.state.mode,'explore');assert.equal(u.errors.length,0)});
await test('介面：重新開始與讀檔取消保留目前進度',async()=>{const u=uiHarness();await u.click({action:'new'});drain(u.game);u.render();await u.click({action:'save'});const before=clone(u.game.state);await u.click({action:'pause'});await u.click({action:'new-confirm'});await u.click({action:'close'});assert.deepEqual(u.game.state,before);await u.click({action:'pause'});await u.click({action:'load'});u.key('Escape');assert.deepEqual(u.game.state,before);await u.click({action:'pause'});await u.click({action:'new-confirm'});await u.click({action:'restart'});assert.equal(u.game.state.dialogue.sceneId,'intro');assert.equal(u.game.state.chapter,0);assert.equal(u.doc.querySelector('.modal-backdrop'),null);assert.equal(u.errors.length,0)});
await test('介面：手札焦點圈、關閉後焦點回到開啟按鈕',async()=>{const u=uiHarness();await u.click({action:'new'});drain(u.game);u.render();const opener=u.find({action:'help'});opener.focus();await u.click({action:'help'});const nodes=u.doc.querySelectorAll();nodes[0].focus();assert(u.key('Tab',{shiftKey:true}).prevented);assert.equal(u.doc.activeElement,nodes.at(-1));assert(u.key('Tab').prevented);assert.equal(u.doc.activeElement,nodes[0]);u.key('Escape');assert.equal(u.doc.activeElement,opener);assert.equal(u.errors.length,0)});
await test('介面：探索互動與技能／物品／目標取消不消耗回合',async()=>{const u=uiHarness();await u.click({action:'new'});drain(u.game);u.render();await u.click({target:'mentor'});assert.equal(u.game.state.dialogue.sceneId,'mentor');drain(u.game);u.render();await u.click({target:'console'});drain(u.game);u.render();assert.equal(u.game.state.mode,'combat');const before=clone(u.game.state);await u.click({action:'skills'});assert(u.find({skill:'debug'}));await u.click({skill:'debug'});assert(u.find({combatTarget:'loop'}));await u.click({action:'cancel-selection'});assert.deepEqual(u.game.state,before);await u.click({action:'battle-items'});await u.click({battleItem:'tea'});u.key('Escape');assert.deepEqual(u.game.state,before);assert(!u.find({combatTarget:'jiang'}));await u.click({action:'attack'});assert.equal(u.game.getActiveActor().id,'su');assert(u.game.state.battle.enemies[0].hp<ENEMIES.loop.maxHp);assert.equal(u.errors.length,0)});
await test('介面：讀檔成功後回到對應畫面，pagehide 可存檔',async()=>{const u=uiHarness();await u.click({action:'new'});u.winHandlers.pagehide();assert.equal(u.data.size,1);const index=u.game.state.dialogue.index;await u.click({action:'advance'});assert.equal(u.game.state.dialogue.index,index+1);await u.click({action:'load'});await u.click({action:'load-now'});assert.equal(u.game.state.dialogue.index,index);assert.equal(u.doc.querySelector('.modal-backdrop'),null);assert.equal(u.errors.length,0)});

function fixture(id='compiler'){const e=fresh();expectOk(e.importSave(snapshots[id]));return e}
function actorFirst(e,id){e.state.battle.turnOrder=[id,...e.state.party.filter(p=>p.id!==id&&p.hp>0).map(p=>p.id)];e.state.battle.turnIndex=0;e.state.battle.currentActorId=id;return e.getActiveActor()}
await test('九項技能的傷害、治療、復活、護盾與專注效果符合設定',()=>{
 for(const id of ['debug','prism','breakpoint']){const e=fixture(),who=Object.values(CHARACTERS).find(c=>c.skills.includes(id)).id,a=actorFirst(e,who),enemy=e.state.battle.enemies[0],hp=enemy.hp,mp=a.mp;expectOk(e.combatAction({actorId:who,kind:'skill',skillId:id,targetId:enemy.id}));assert.equal(a.mp,mp-SKILLS[id].cost);assert.equal(hp-enemy.hp,Math.max(1,Math.round(a.atk*SKILLS[id].power-enemy.def*(id==='prism'?.5:1))));if(SKILLS[id].effect==='weaken')assert.equal(enemy.weakened,1)}
 {const e=fixture('race'),a=actorFirst(e,'jiang');a.buff=1;const before=e.state.battle.enemies.map(x=>x.hp),mp=a.mp;expectOk(e.combatAction({actorId:a.id,kind:'skill',skillId:'recursion'}));e.state.battle.enemies.forEach((enemy,i)=>assert.equal(before[i]-enemy.hp,Math.round(a.atk*1.22*1.35-enemy.def)));assert.equal(a.buff,0);assert.equal(a.mp,mp-13)}
 {const e=fixture(),a=actorFirst(e,'su'),target=e.state.party[0];target.hp=1;expectOk(e.combatAction({actorId:a.id,kind:'skill',skillId:'heal',targetId:target.id}));assert.equal(target.hp,1+58+4*(a.level-1))}
 for(const dead of [false,true]){const e=fixture(),a=actorFirst(e,'jiang'),target=e.state.party.find(p=>p.id==='su');target.hp=dead?0:1;expectOk(e.combatAction({actorId:a.id,kind:'skill',skillId:'restore',targetId:target.id}));assert.equal(target.hp,dead?Math.ceil(target.maxHp*.45):56)}
 {const e=fixture(),a=actorFirst(e,'su');for(const p of e.state.party)p.hp=1;expectOk(e.combatAction({actorId:a.id,kind:'skill',skillId:'inspire'}));assert(e.state.party.every(p=>p.hp===23&&p.buff===1))}
 {const e=fixture(),a=actorFirst(e,'shen');for(const p of e.state.party)p.shield=60;expectOk(e.combatAction({actorId:a.id,kind:'skill',skillId:'firewall'}));assert(e.state.party.every(p=>p.shield===66))}
 {const e=fixture(),a=actorFirst(e,'shen');for(const p of e.state.party){p.hp=1;p.mp=12}expectOk(e.combatAction({actorId:a.id,kind:'skill',skillId:'sync'}));assert(e.state.party.every(p=>p.hp===15));assert.equal(a.mp,8);assert(e.state.party.filter(p=>p.id!==a.id).every(p=>p.mp===20))}
});
await test('防禦降低傷害、回復專注；撤退不取得獎勵',()=>{const outcomes=[];for(const kind of ['attack','guard']){const e=fixture('loop');for(const p of e.state.party)p.mp=0;const hp=e.state.party[0].hp;expectOk(e.combatAction({actorId:'jiang',kind}));assert.equal(e.state.party[0].mp,kind==='guard'?6:3);expectOk(e.combatAction({actorId:'su',kind:'guard'}));outcomes.push(hp-e.state.party[0].hp);const gold=e.state.gold,wins=e.state.battlesWon;expectOk(e.fleeBattle());assert.equal(e.state.gold,gold);assert.equal(e.state.battlesWon,wins);assert(!e.state.flags.loopCleared)}assert(outcomes[1]<outcomes[0])});
let fuzzStats={attempts:0,rejected:0,accepted:0};
await test('逐欄位刪除的損毀存檔模糊測試：拒絕不改進度，接受後仍可操作',()=>{
 function paths(v,at=[]){if(!v||typeof v!=='object')return [];const out=[];for(const k of Object.keys(v)){out.push([...at,k]);out.push(...paths(v[k],[...at,k]))}return out}
 for(const name of ['intro','loop','compilerVictory','endingtrue1']){const original=JSON.parse(snapshots[name]);for(const path of paths(original.state)){const payload=clone(original),e=fresh();e.newGame();const before=clone(e.state);let target=payload.state;for(const key of path.slice(0,-1))target=target[key];delete target[path.at(-1)];fuzzStats.attempts++;const label=name+'/'+path.join('.');const r=e.importSave(JSON.stringify(payload));if(!r.ok){fuzzStats.rejected++;assert.deepEqual(e.state,before,label);continue}fuzzStats.accepted++;assert.doesNotThrow(()=>{e.getObjective();e.getAvailableInteractions();e.getAvailableRegions();e.getEnding();e.getActiveActor();if(e.state.mode==='dialogue')drain(e);if(e.state.mode==='combat')fight(e);if(e.state.mode==='victory'){e.dismissVictory();drain(e)}healthy(e)},label)}}
 console.log(`INFO 逐欄位刪除 ${fuzzStats.attempts} 例：安全拒絕 ${fuzzStats.rejected}，可安全操作 ${fuzzStats.accepted}`)
});

console.log(`\n額外 QA：${results.filter(r=>r.ok).length}/${results.length} 通過。`);
if(results.some(r=>!r.ok))process.exitCode=1;
