import assert from 'node:assert/strict';
import {Engine} from './engine.js';
import {REGIONS, SCENES, SAVE_KEY, SKILLS} from './story.js';
let tests=0;
const test=(name,fn)=>{fn();tests++;console.log(`PASS ${name}`)};
const storage=()=>{const data={};return {getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=v,removeItem:k=>delete data[k]}};
function finishDialogue(e,choice=0){let steps=0;while(e.state.mode==='dialogue'){assert.ok(++steps<100);const result=e.state.dialogue.choices.length?e.choose(e.state.dialogue.sceneId==='checksum'?1:choice):e.advanceDialogue();assert.ok(result.ok,result.message);}return e.state.mode;}
function roundTrip(e){const clone=new Engine({autoSave:false});const result=clone.importSave(e.exportSave());assert.ok(result.ok,result.message);const original=structuredClone(e.state);const loaded=structuredClone(clone.state);delete original.revision;delete loaded.revision;assert.deepEqual(loaded,original);return clone;}
function fight(e){let actions=0;while(e.state.mode==='combat'){assert.ok(++actions<300,'battle should terminate');const actor=e.getActiveActor(),down=e.state.party.find(p=>p.hp<=0),hurt=[...e.state.party].filter(p=>p.hp>0).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];let action={actorId:actor.id,kind:'attack'};if(down&&e.state.inventory.revive>0)action={...action,kind:'item',itemId:'revive',targetId:down.id};else if(actor.id==='su'&&hurt.hp/hurt.maxHp<.6&&actor.mp>=8)action={...action,kind:'skill',skillId:'heal',targetId:hurt.id};else if(hurt.hp/hurt.maxHp<.25&&e.state.inventory.tea>0)action={...action,kind:'item',itemId:'tea',targetId:hurt.id};else if(actor.id==='shen'&&e.state.battle.enemies.some(x=>x.hp>0&&x.intent.kind==='sweep')&&actor.mp>=9)action={...action,kind:'skill',skillId:'firewall'};else {const id=actor.id==='jiang'?(e.state.battle.enemies.filter(x=>x.hp>0).length>1?'recursion':'debug'):actor.id==='su'?'prism':'breakpoint';if(actor.skills.includes(id)&&actor.level>=(SKILLS[id].unlockLevel??1)&&actor.mp>=SKILLS[id].cost)action={...action,kind:'skill',skillId:id};}const result=e.combatAction(action);assert.ok(result.ok,result.message);roundTrip(e);}assert.equal(e.state.mode,'victory',e.state.battle?.log.slice(-10).join('\n'));return actions;}
function start(){const e=new Engine({autoSave:false});assert.ok(e.newGame().ok);finishDialogue(e);return e;}
function visit(e,id){assert.ok(e.interact(id).ok,`interact ${id}`);finishDialogue(e);}
function victory(e){fight(e);assert.ok(e.dismissVictory().ok);finishDialogue(e);}

test('data maps and authored narrative are complete',()=>{assert.ok(Object.values(SCENES).reduce((n,s)=>n+s.length,0)>=100);for(const r of Object.values(REGIONS)){assert.equal(r.map.length,11);assert.ok(r.map.every(row=>row.length===15));assert.equal(new Set(r.targets.map(t=>t.id)).size,r.targets.length);for(const t of r.targets)assert.ok(!['#','T','~'].includes(r.map[t.y][t.x]),`${t.id} on blocker`);}});
test('initial, dialogue and branching state round-trip',()=>{const e=new Engine({autoSave:false});e.newGame();roundTrip(e);while(!e.state.dialogue.choices.length)e.advanceDialogue();assert.equal(e.advanceDialogue().ok,false);assert.equal(e.choose(-1).ok,false);assert.equal(e.choose(999).ok,false);assert.ok(e.choose(0).ok);roundTrip(e);assert.equal(e.choose(0).ok,false);finishDialogue(e);assert.equal(e.state.relationships.su,2);});
test('world gates, collision and safe navigation',()=>{const e=start();assert.equal(e.travel('library').ok,false);assert.equal(e.travel('missing').ok,false);assert.equal(e.interact('console').ok,false);assert.equal(e.move(2,0).ok,false);assert.equal(e.moveTo(-1,0).ok,false);for(const t of e.getRegion().targets){assert.ok(e.navigate(t.id).ok);assert.ok(e.getNearbyTargets().some(x=>x.id===t.id));}assert.ok(e.moveTo(6,8).ok);assert.equal(e.rest().ok,false);assert.ok(e.interact('snack').ok);assert.equal(e.state.mode,'dialogue');});
test('rest recovers everything and purchase is bounded',()=>{const e=start();e.state.party[0].hp=0;e.state.party[1].mp=0;e.state.party[1].shield=10;e.interact('snack');finishDialogue(e);assert.ok(e.state.party.every(p=>p.hp===p.maxHp&&p.mp===p.maxMp&&p.shield===0));const count=e.state.inventory.tea;assert.ok(e.buyItem('tea').ok);assert.equal(e.state.inventory.tea,count+1);assert.equal(e.buyItem('tea',100).ok,false);assert.equal(e.buyItem('tea',-1).ok,false);assert.equal(e.buyItem('rice',3).ok,false);});
test('invalid items do not consume resources',()=>{const e=start();const inv=structuredClone(e.state.inventory);assert.equal(e.useItem('tea','jiang').ok,false);assert.equal(e.useItem('revive','jiang').ok,false);assert.equal(e.useItem('rice').ok,false);assert.deepEqual(e.state.inventory,inv);e.state.party[0].hp=0;assert.equal(e.useItem('tea','jiang').ok,false);assert.ok(e.useItem('revive','jiang').ok);assert.ok(e.state.party[0].hp>0);});
test('duplicate one-time interactions do not farm rewards',()=>{const e=start();visit(e,'notice');const count=e.state.inventory.tea;visit(e,'notice');assert.equal(e.state.inventory.tea,count);visit(e,'suTalk');const rel=e.state.relationships.su;visit(e,'suTalk');assert.equal(e.state.relationships.su,rel);});
test('malformed saves fail atomically and storage errors are safe',()=>{const e=start();const before=e.exportSave();for(const raw of ['','{','null','[]','{}',JSON.stringify({version:999,state:e.state})]){assert.equal(e.importSave(raw).ok,false);assert.deepEqual(JSON.parse(e.exportSave()).state,JSON.parse(before).state);}const p=JSON.parse(before);p.state.party[0].hp=-1;assert.equal(e.importSave(JSON.stringify(p)).ok,false);assert.equal(e.save({setItem(){throw Error('quota')}}).ok,false);assert.equal(e.load({getItem(){throw Error('blocked')}}).ok,false);const st=storage();assert.ok(e.save(st).ok);assert.equal(e.getSaveSummary(st).chapter,1);assert.ok(e.load(st).ok);assert.ok(st.getItem(SAVE_KEY));});
test('invalid combat commands preserve the turn and resources',()=>{const e=start();visit(e,'mentor');visit(e,'console');const before=structuredClone(e.state);assert.equal(e.combatAction({actorId:'su',kind:'attack'}).ok,false);assert.equal(e.combatAction({kind:'attack',targetId:'ghost'}).ok,false);assert.equal(e.combatAction({kind:'skill',skillId:'heal'}).ok,false);assert.equal(e.combatAction({kind:'item',itemId:'revive',targetId:'jiang'}).ok,false);assert.equal(e.combatAction({kind:'nope'}).ok,false);assert.deepEqual(e.state,before);});
test('defeat can reload, retry, and retreat without losing story',()=>{const e=start();visit(e,'mentor');visit(e,'console');const initialItems=structuredClone(e.state.inventory);e.state.party.forEach(p=>{p.hp=1;});while(e.state.mode==='combat')e.combatAction({kind:'guard'});assert.equal(e.state.mode,'defeat');roundTrip(e);assert.ok(e.retryBattle().ok);assert.deepEqual(e.state.inventory,initialItems);assert.ok(e.state.party.every(p=>p.hp===p.maxHp));assert.ok(e.retreat().ok);assert.equal(e.state.mode,'explore');assert.ok(e.getNearbyTargets().some(t=>t.kind==='rest'));assert.ok(e.state.flags.assigned);assert.ok(!e.state.flags.loopCleared);});
for(const ending of [0,1])test(`full story with meaningful tactics, ending choice ${ending}`,()=>{const e=start();visit(e,'notice');visit(e,'suTalk');visit(e,'campusEcho');visit(e,'mentor');visit(e,'console');victory(e);assert.equal(e.state.level,2);assert.ok(e.travel('library').ok);visit(e,'librarian');visit(e,'book');visit(e,'archive');assert.ok(e.state.flags.checksumSolved);visit(e,'sentinel');victory(e);assert.equal(e.state.party.length,3);assert.ok(e.travel('server').ok);visit(e,'memory');visit(e,'shenTalk');visit(e,'race');victory(e);visit(e,'serverRest');visit(e,'beast');victory(e);visit(e,'serverRest');visit(e,'core');fight(e);e.dismissVictory();finishDialogue(e,ending);assert.equal(e.state.mode,'ending');assert.ok(e.state.flags.finished);assert.equal(e.state.battlesWon,5);assert.equal(e.state.ending,ending===0?'together':'open');assert.equal(e.state.quests.filter(q=>q.status==='done').length,9);assert.ok(e.getEnding().epilogue.length>20);roundTrip(e);console.log('  Ending stats',e.state.level,e.state.relationships,e.state.party.map(p=>p.hp));});
console.log(`\n${tests} engine tests passed.`);
